### ISSUE TITLE
Do you need sources?

### ISSUE THREAD

**Issue by Onfroygmx** [zdharma-continuum/I_WANT_TO_HELP#1]
Don't know if it can help,  but I previously made some backups of zinit:

![image](https://user-images.githubusercontent.com/25054585/139526279-72fd7872-0926-4791-bacd-5bc5e8dfc695.png)

I can upload them somewhere if you want.
Onf

**Comment by alichtman** [comment]
I have the complete history. Thanks

**Comment by Onfroygmx** [comment]
OK, good luck.
Never used it, just tested it.

Onf
