### ISSUE TITLE
Adding a repo/wiki to help with migration

### ISSUE THREAD

**Issue by BLucky-gh** [zdharma-continuum/I_WANT_TO_HELP#12]
I believe a repo or wiki with steps to migrate from the deleted versions of apps where the apps are broken due to the deletion (zinit for example) would be very useful. Some people may not know where to change what to migrate to this org's fork/mirror of the stuff. If needed I might try to help writing the help page/wiki/whatever.

**Comment by alichtman** [comment]
1. Make a commit like this in your zshrc, updating `zdharma` to `zdharma-continuum` refernces. https://github.com/alichtman/dotfiles/commit/d70fa490d8b6bbeb85359501a6e835f5d579743b
2. Set zinit git remote url: `$  git remote set-url origin git@github.com:zdharma-continuum/zinit.git && git pull`

Will approve a PR with a wiki or doc for this.

**Comment by alichtman** [comment]
Once the website is up, we could add this to the front page of the wiki.

**Comment by BLucky-gh** [comment]
Since apparently only members with write access to the repository can create a wiki, and you can't include *creating* a wiki in a pull request, I can't submit a PR with the wiki. You can check [the wiki page at my fork of `zinit`](https://github.com/BLucky-gh/zinit/wiki) and if it's a page you'd approve, please create a blank wiki on your repo so that I can suggest the edits.

**Comment by pschmitt** [comment]
@alichtman can you please allow the other members of the zdharma-continuum org to at least edit the wiki on the zinit repo?

**Comment by alichtman** [comment]
1. Enabled discussions on `zinit`.
2. @BLucky-gh @pschmitt invited you to `zinit` with write permissions

**Comment by alichtman** [comment]
I'll leave this open until the wiki is added

**Comment by pschmitt** [comment]
Created the wiki :1st_place_medal:

**Comment by pschmitt** [comment]
I think we can close this issue.

We should link to the [migration wiki page](https://github.com/zdharma-continuum/zinit/wiki/Migration-to-zdharma-continuum) from zinit's README.md

**Comment by alichtman** [comment]
Approved all relevant PRs.
