### ISSUE TITLE
Community tools

### ISSUE THREAD

**Issue by pschmitt** [zdharma-continuum/I_WANT_TO_HELP#13]
Hej fellow zinit users,

What do you guys think about creating the following?

- a matrix and/or IRC channel
- a new subreddit (since r/zinit seems to be doomed as well)
- enabling GH discussions on the main repo (zdharma-continuum/zinit)

**Comment by NorthIsUp** [comment]
or discord...

**Comment by crivotz** [comment]
I've always thought that a single access point is the best thing to manage communications. +1 for GH discussions.

**Comment by alichtman** [comment]
I've enabled discussions on this repo.

**Comment by pschmitt** [comment]
I'm a bit confused about where to start discussions now since both this here repo and zinit have the feature enabled, but thanks! 😅

Should we maybe add a disclaimer in the READMEs about where to discuss particular topics? It might also make sense to instruct users to first use discussions before raising an issue on the main repo.
In the past most issues where related to particular software and what ices to use for them. IMHO this does not warrant an issue for instance and should be a discussion and/or wiki entry.

**Comment by alichtman** [comment]
I'm also confused about where the right place to put certain discussions is. Maybe a `discussions` repo is a good catch-all for organization-related discussions?

**Comment by pschmitt** [comment]
I don't think that this is a good idea.
What I would do is disable everything except:

- zinit issues
- zinit discussions
- Gitter

yes, I am suggesting to archive this repo :D

**Comment by pschmitt** [comment]
I don't necessarily think that this would be a good idea.
Gitter and zinit discussions should be more than enough.

If it was only up to me we'd disable everything except zinit issues, discussions and Gitter.
Yes, I'm suggesting to archive this repo :D

**Comment by alichtman** [comment]
Those changes are ok by me. You can make them.
