### ISSUE TITLE
🎯 Hunt for missing repos!

### ISSUE THREAD

**Issue by pschmitt** [zdharma-continuum/I_WANT_TO_HELP#15]
While migrating stuff to zdharma-continuum I noticed that a few repos are neither available via softwareheritage.org,  the wayback machine nor google cache.

If anyone has these on disk please let me know:

- [x] https://github.com/zservices/redis (seems to be outdated though...)
- [x] https://github.com/zinit-zsh/zinit-console
- [x] https://github.com/psprint/zsh-editing-workbench
- [x] https://github.com/psprint/zsh-cmd-architect
- [ ] z-a-turbo-annexes

Feel free to add a comment if you are missing a particular repo.

**Comment by dmitmel** [comment]
>  https://github.com/zservices/redis

https://archive.softwareheritage.org/browse/directory/cb287704c1edfa1467741ef3e3588930da587b98/?origin_url=https://github.com/zdharma/zredis&revision=161782cd6d945316fb6b9651d1d0438ff9a0e52f&snapshot=b764f1783948f8db3d37bd47233d59f1b990d511

>  https://github.com/zinit-zsh/zinit-console

This one was probably a fork: <https://github.com/tortious/zplugin-console>, but I found a newer (and differently named) version which seems to have full commit history: <https://github.com/NorthIsMirror/zplugin-view>. Proof: [Google-cached page](<https://webcache.googleusercontent.com/search?q=cache:kSq6RjvG9ggJ:https://github.com/orgs/zinit-zsh/repositories%3Flanguage%3Dshell+>) as of 2021-09-01 of the repositories list of zinit-zsh says that the latest commit in zinit-console was on 2020-02-07.

**Comment by Freed-Wu** [comment]
<psprint/zsh-editing-workbench> and <psprint/zsh-cmd-architect> also disappeared. Any method to recover them?

**Comment by pschmitt** [comment]
> <psprint/zsh-editing-workbench> and <psprint/zsh-cmd-architect> also disappeared. Any method to recover them?

I've restored both from softwareheritage.org. Here you go:

- https://github.com/zdharma-continuum/zsh-cmd-architect
- https://github.com/zdharma-continuum/zsh-editing-workbench

**Comment by pschmitt** [comment]
> > [zservices/redis](https://github.com/zservices/redis)
> 
> [unixorn/redis](https://github.com/unixorn/redis). This is the only fork, but it is severely outdated.
> 
> > [zinit-zsh/zinit-console](https://github.com/zinit-zsh/zinit-console)
> 
> This one was probably a fork: [tortious/zplugin-console](https://github.com/tortious/zplugin-console), but I found a newer (and differently named) version which seems to have full commit history: [NorthIsMirror/zplugin-view](https://github.com/NorthIsMirror/zplugin-view). Proof: [Google-cached page](https://webcache.googleusercontent.com/search?q=cache:kSq6RjvG9ggJ:https://github.com/orgs/zinit-zsh/repositories%3Flanguage%3Dshell+) as of 2021-09-01 of the repositories list of zinit-zsh says that the latest commit in zinit-console was on 2020-02-07.

Thanks for digging!

I've forked:
- https://github.com/NorthIsMirror/zplugin-view to https://github.com/zdharma-continuum/zinit-console
- https://github.com/unixorn/redis to https://github.com/zdharma-continuum/redis

**Comment by NorthIsUp** [comment]
my NorthIsMirror org is just a full dump of all the repos from software heritage + anything I had locally, so most of the missing stuff should be there.

the different name is funny tho...

**Comment by pschmitt** [comment]
> my NorthIsMirror org is just a full dump of all the repos from software heritage + anything I had locally, so most of the missing stuff should be there.

Thanks for setting this up! It definitely helped getting the stuff back up under the zdharma-continuum org.
99% is done now, only a few repos didn't survive (see above)

> the different name is funny tho...

psprint probably wanted to rename the project but forgot to change the repo url 🤷‍♂️

**Comment by yutkat** [comment]
I wat to add z-a-readurl. Here(https://github.com/yutkat/z-a-readurl) is my fork.

**Comment by pschmitt** [comment]
> I wat to add z-a-readurl. Here([yutkat/z-a-readurl](https://github.com/yutkat/z-a-readurl)) is my fork.

https://github.com/zdharma-continuum/zinit-annex-readurl/ :eyes:

**Comment by yutkat** [comment]
@pschmitt Thank you very much!

**Comment by alichtman** [comment]
I believe we're done with the migration.
