### ISSUE TITLE
Automated Security Analysis + Linting

### ISSUE THREAD

**Issue by alichtman** [zdharma-continuum/I_WANT_TO_HELP#16]
It would be great if we could stand up an automated security analysis + linting pipeline for zinit + other plugins. `shellcheck`, or other like tools. Idk what the state of the art `zsh` security tooling is.

**Comment by pschmitt** [comment]
Had similar thoughts: https://github.com/zdharma-continuum/zinit/discussions/21

I've spent some time on creating a container that we could use at least for testing in CI. See the ci branch on my zinit fork.

**Comment by alichtman** [comment]
Just saw your post. Have some thoughts, but want to flesh them out before I respond. My general sentiment is that I'm supportive of any automated testing that catches security / implementation errors, or auto-publishes documentation. I'll approve any permissions you need in order to make it happen

**Comment by NorthIsUp** [comment]
`shellcheck` sadly isn't for zsh, much of what is in zdharma uses "advanced" zsh features or required a new-ish version of zsh. both of which break `shellcheck`.

my kingdom for a good zsh linter tho!

**Comment by alichtman** [comment]
Discussion under zinit issues.
