### ISSUE TITLE
Additional repo forks found

### ISSUE THREAD

**Issue by mattmc3** [zdharma-continuum/I_WANT_TO_HELP#2]
- [https://github.com/mr-salty/Zsh-100-Commits-Club](Zsh-100-Commits-Club)
- [https://github.com/caseyrhanson/zinit-configs](https://github.com/caseyrhanson/zinit-configs)
- [https://github.com/HarHarLinks/zsh-diff-so-fancy](https://github.com/HarHarLinks/zsh-diff-so-fancy)
- [https://github.com/Diagonactic/zconvey](https://github.com/Diagonactic/zconvey) - old, but all I could find
- [https://github.com/issenn/zui](https://github.com/issenn/zui) - unclear if this is the most recent

**Comment by mattmc3** [comment]
Here's one from his personal repo [https://github.com/psprin](https://github.com/psprint) I found:

- [https://github.com/Manny27nyc/zsh-navigation-tools](https://github.com/Manny27nyc/zsh-navigation-tools)

**Comment by kite12580** [comment]
- https://github.com/tony/za-bin-gem-node - latest of zinit-zsh/z-a-bin-gem-node

**Comment by UncleClapton** [comment]
Hey there!

I've uploaded my local copies of the zinit extensions I am using, in the hopes that somebody has an interest in keeping these alive. I have no plan for maintaining these packages, but I will keep them on my account for prosperity and to give others a chance to pick up the pieces.

* https://github.com/UncleClapton/z-a-rust
* https://github.com/UncleClapton/z-a-as-monitor
* https://github.com/UncleClapton/z-a-patch-dl
* https://github.com/UncleClapton/z-a-bin-gem-node

**Comment by r4lv** [comment]
I have a local copy of `zdharma/zsh-diff-so-fancy`, which I uploaded here:

- https://github.com/r4lv/zsh-diff-so-fancy

**Comment by aamehedi** [comment]
1. https://github.com/aamehedi/z-a-rust
2. https://github.com/aamehedi/z-a-patch-dl
3. https://github.com/aamehedi/z-a-bin-gem-node
4. https://github.com/aamehedi/z-a-as-monitor
5. https://github.com/aamehedi/fast-syntax-highlighting

**Comment by vladdoster** [comment]
I suspected something like this would happen when his personal site started linking to ads. 

Thank you for starting this organization. 

I'd be more than happy to get the wiki back up if you could add me to the organization.

**Comment by alichtman** [comment]
Pulled them all up to this comment.
