### ISSUE TITLE
I was committer to zdharma/z-a-meta-plugins

### ISSUE THREAD

**Issue by luong-komorebi** [zdharma-continuum/I_WANT_TO_HELP#3]
This is proof: https://github.com/luong-komorebi/z-a-meta-plugins

I would love to contribute two things:
1. There was a zdharma/null repo before, to do cleanup tasks, hacking, cleaning up

![image](https://user-images.githubusercontent.com/15828926/139596093-a386a135-dcba-4146-8d20-6a897e29ebfe.png)

2. z-a-meta-plugins. This repos was a meta-repo that contains quick installation script to many packages. I had one of the latest patch of it.

**Comment by alichtman** [comment]
Verified previous contributor status. Invited to maintain the org.

Feel free to add those (you should have repo creation privs once you accept the invite).

**Comment by luong-komorebi** [comment]
Thanks @alichtman . I will casually transfer those repos to the org
