### ISSUE TITLE
zinit Annexes

### ISSUE THREAD

**Issue by pschmitt** [zdharma-continuum/I_WANT_TO_HELP#7]
Since [zsh-zinit](https://github.com/zinit-zsh) didn't survive the snap I've reuploaded the repos of some annexes:

- [x] https://github.com/pschmitt/z-a-as-monitor
- [x] https://github.com/pschmitt/z-a-bin-gem-node
- [x] https://github.com/pschmitt/z-a-default-ice
- [x] https://github.com/pschmitt/z-a-patch-dl
- [x] https://github.com/pschmitt/z-a-rust

**Comment by pschmitt** [comment]
I see that most these are now part of zdharma-continuum, the only one remaining is [z-a-default-ice](https://github.com/pschmitt/z-a-default-ice)

**Comment by alichtman** [comment]
Done
