### ISSUE TITLE
A few more repo forks

### ISSUE THREAD

**Issue by aamehedi** [zdharma-continuum/I_WANT_TO_HELP#8]
Here is a list of repo forks, I was able to figure out with the help of **Wayback Machine** (Thanks to Archive Team and the WARC). You can still browse the repo pages from [zinit-zsh](https://web.archive.org/web/20210726135702/https://github.com/zinit-zsh) and [zdharma](https://web.archive.org/web/20200309073419/https://github.com/zdharma).
After getting the exact repo names from there, I search in github and tired find the most updated fork. Here is the list:

- https://github.com/davydkov/zinit-configs
- https://github.com/MenkeTechnologies/zconvey  (I believe this one has more updated commit than the https://github.com/Diagonactic/zconvey)
- https://github.com/agkozak/zbrowse
- https://github.com/zdharma-mirror/zsh-startify
- https://github.com/uselessfire/pm-perf-test
- https://github.com/Spread0x/zshelldoc
- https://github.com/issenn/zzcomplete
- https://github.com/onaforeignshore/zinit-crasis
- https://github.com/Spread0x/zui
- https://github.com/NorthIsUp/zsh-github-issues
- https://github.com/agkozak/zsh-lint
- https://github.com/disco0/z-a-unscope
- https://github.com/issenn/z-a-submods
- https://github.com/julien-noblet/z-a-man
- https://github.com/tortious/zplugin-console
- https://github.com/issenn/zinit-vim-syntax

I still wasn't to get a hold of the following repos. If anyone have a forks of these or have them locally, please upload in a repo and share with us. Thanks!

- z-a-default-ice
- z-a-turbo-annexes
- z-a-test

**Comment by pschmitt** [comment]
I have uploaded a bunch of annexes (z-a-default-ice notably):
See https://github.com/zdharma-continuum/I_WANT_TO_HELP/issues/7

**Comment by mortenscheel** [comment]
I tried installing https://github.com/issenn/z-a-submods but it didn't work for me. The submod was never pulled.

**Comment by ryaminal** [comment]
What's the process for getting these into the zdharma-continuum org? The ones I'm in need of are z-a-unscope and z-a-submods. I'm fetching these through the z-a-meta-plugins stuff. I've checked the ones(unscope and submodes) linked above versus my local copies and they are either at the same level or slightly newer.

I assume there is some desire to check these repos for malicious commits, yeah?

**Comment by aamehedi** [comment]
@alichtman would you please pull these repos?

**Comment by NorthIsUp** [comment]
uploaded a bunch of my local clones:

https://github.com/NorthIsUp/zdharma-fast-syntax-highlighting.git
https://github.com/NorthIsUp/zdharma-history-search-multi-word.git
https://github.com/NorthIsUp/zdharma-z-p-submods.git
https://github.com/NorthIsUp/zdharma-zsh-diff-so-fancy.git
https://github.com/NorthIsUp/zdharma-zui.git

**Comment by alichtman** [comment]
I've preserved my own workflow and won't be taking over the entire archiving process. Will get to the remaining repos when I have time. I have invited a few other people with demonstrated involvement in the zsh community to help with archiving.

**Comment by alichtman** [comment]
> NorthIsUp/zsh-diff-so-fancy

I also explicitly do not want to support this plugin. It's poorly designed (ships a submodule that needs to be updated manually instead of installing `diff-so-fancy` with a package manager and running the `git config` line to configure it).

**Comment by alichtman** [comment]
If someone compiles an updated list of missing modules, I can fork them into the org.

**Comment by NorthIsUp** [comment]
> On the other hand, not having it will break workflows (regardless of my feelings about them).

I think step one is just getting the latest forks of _everything_, once we have forks we can fix or depricate.

**Comment by alichtman** [comment]
That's cool, thanks :)

**Comment by pschmitt** [comment]
I completed the migration of the following orgs:

- [x] [Zsh-Packages](https://archive.softwareheritage.org/browse/search/?q=github.com%2FZsh-Packages&with_visit=true&with_content=true&visit_type=git)
- [x] [zinit-zsh](https://archive.softwareheritage.org/browse/search/?q=github.com%2Fzinit-zsh&with_visit=true&with_content=true&visit_type=git)

**Comment by pschmitt** [comment]
If I am not mistaken all of the repos listed in the above comments are now migrated to zdharma-continuum.

The only thing that's left to do here is to maybe get https://github.com/zdharma-continuum/zconvey up to date with https://github.com/MenkeTechnologies/zconvey

**Comment by aamehedi** [comment]
Closing this as almost all of the repos are found and migrated :)
