### ISSUE TITLE
domain name

### ISSUE THREAD

**Issue by ryaminal** [zdharma-continuum/I_WANT_TO_HELP#9]
There are several domain names and TLDs available. zdharma.org is not, available, but maybe that's okay.

I vote we use zinit.dev. I'm willing to buy the domain but figured I'd ask so we don't step on anyone's toes.

**Comment by pschmitt** [comment]
Great idea.

zinit-z.sh is available as well 😇

**Comment by alichtman** [comment]
Imo zdharma-continuum.org would be best

**Comment by alichtman** [comment]
`zdharma-continuum.org` is available. Keeps it in line with the previous version (`zdharma.org`). Maybe that?

**Comment by pschmitt** [comment]
Maybe we should create a poll :)

**Comment by alichtman** [comment]
Let's use the free GitHub IO domain and not do anything custom. Lower completely is better + the domain is inherently tied to the source code.

**Comment by pschmitt** [comment]
> Let's use the free GitHub IO domain and not do anything custom. Lower completely is better + the domain is inherently tied to the source code.

That's probably the very best thing we can do for the moment, yeah.
I wish z-d-h-a-r-m-a---c-o-n-t-i-n-u-u-m wasn't so long to type :D

**Comment by alichtman** [comment]
Yeah, I didn't want to change the org name and 'continuum' was a good suffix. And changing the name is a bit of a breaking change at this point.

**Comment by pschmitt** [comment]
> Yeah, I didn't want to change the org name and 'continuum' was a good suffix. And changing the name is a bit of a breaking change at this point.

True, true. While we're somewhat on the topic of branding would you please add a profile pic to @zdharma-continuum?
Here are some candidates: https://github.com/zdharma-continuum/zinit/discussions/17#discussioncomment-1599324

**Comment by pschmitt** [comment]
btw I restored https://github.com/zdharma-continuum/zdharma-continuum.github.io (-> zdharma-continuum.github.io) - even though it's not been updated in years.

**Comment by alichtman** [comment]
Closing, as we're using GitHub.io
